---
# tasks file for nginx

- include: pacman.yml
  when: ansible_pkg_mgr == 'pacman'
  tags:
    - nginx
    - pacman

- name: get pre-run stat of nginx config
  stat:
    follow: "{{ nginx_config_follow | default(omit) }}"
    get_checksum: yes
    path: "{{ nginx_config_dest }}"
  register: nginx_config_st_pre
  notify:
    - check nginx config
  tags:
    - nginx
    - config
    - service

- include: service.yml
  tags:
    - nginx
    - service
