---
# tasks file for nginx
- name: include package-manager-specific vars
  include_vars: '{{ ansible_pkg_mgr }}.yml'
  when: ansible_pkg_mgr is defined
  tags:
    - always

- name: include distribution-specific vars
  include_vars: '{{ ansible_distribution }}.yml'
  when: ansible_distribution is defined
  tags:
    - always

- name: include package tasks
  include: package.yml
  when: ansible_pkg_mgr is defined
  tags:
    - nginx.package

- name: include pip tasks
  include: pip.yml
  when: '"certbot-nginx" not in nginx_pkg_prereqs'
  tags:
    # Tagged with package in case nginxparser/certbot-nginx isn't available
    # through the package manager
    - nginx.package
    - nginx.pip
