---
- name: configure nginx service
  service:
    arguments: "{{ nginx_service_arguments | default(omit) }}"
    enabled: "{{ nginx_service_enabled | default(omit) | bool }}"
    name: "{{ nginx_service_name }}"
    pattern: "{{ nginx_service_pattern | default(omit) }}"
    runlevel: "{{ nginx_service_runlevel | default(omit) }}"
    sleep: "{{ nginx_service_sleep | default(omit) }}"
    enabled: "{{ nginx_service_enabled }}"
  tags:
    - nginx
    - service
