---
# handlers file for nginx

- name: get post-run stat of nginx config
  stat:
    follow: "{{ nginx_config_follow | default(omit) }}"
    get_checksum: yes
    path: "{{ nginx_config_dest }}"
  register: nginx_config_st_post
  # Always trigger checksum comparisons
  changed_when: nginx_service_restarted_on_change | bool
  notify:
    - compare nginx config checksums
  tags:
    - nginx
    - config
    - service

- name: compare nginx config checksums
  debug: trigger nginx restart
  changed_when: nginx_config_st_pre.stat.checksum != nginx_config_st_post.stat.checksum
  notify: restart nginx service
  tags:
    - nginx
    - config
    - service

- name: restart nginx service
  service:
    arguments: "{{ nginx_service_arguments | default(omit) }}"
    name: "{{ nginx_service_name }}"
    pattern: "{{ nginx_service_pattern | default(omit) }}"
    runlevel: "{{ nginx_service_runlevel | default(omit) }}"
    sleep: "{{ nginx_service_sleep | default(omit) }}"
    state: restarted
  tags:
    - nginx
    - service
