---
- name: check nginx config
  stat:
    follow: "{{ nginx_follow | default(omit) }}"
    get_checksum: yes
    path: "{{ nginx_config_dest }}"
  register: nginx_config_stat_post
  notify:
    - compare nginx config stats
  tags:
    - nginx
    - config
    - service

- name: compare nginx config stats
  debug: trigger nginx restart
  changed_when: nginx_config_stat_pre.checksum != nginx_config_stat_post.checksum
  notify: restart nginx service

# handlers file for nginx
- name: restart nginx service
  service:
    arguments: "{{ nginx_service_arguments | default(omit) }}"
    name: "{{ nginx_service_name }}"
    pattern: "{{ nginx_service_pattern | default(omit) }}"
    runlevel: "{{ nginx_service_runlevel | default(omit) }}"
    sleep: "{{ nginx_service_sleep | default(omit) }}"
    state: restarted
  # Only perform restart if service is enabled
  when: nginx_service_enabled | default('no') | bool
  tags:
    - nginx
    - service
